# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
notifications:
  email: false
matrix:
  include:
    - os: osx
      julia: 1.0
    - os: linux
      julia: 1.0
    - os: linux
      julia: nightly
  allow_failures:
    - julia: nightly
branches:
  only: master

before_install:

script:
 - julia -e 'Pkg.clone(pwd()); Pkg.build("ClassicNNLS");'

after_success:
